osx_image: xcode12.3
addons: 
homebrew:
  packages:
  - carthage
jobs:
  include:
  - stage: Validate Pods
    script: "./Scripts/pod-lint.sh"
    os: osx
    osx_image: xcode12.3
  - stage: release new version
    script: "./Scripts/travis/new-release.sh"
    os: osx
    osx_image: xcode12.3
    if: branch = master AND type = push AND fork = false
  - stage: deploy to cocoapods
    script: "./Scripts/travis/deploy-to-cocoapods.sh"
    os: osx
    osx_image: xcode12.3
    if: branch = master AND type = push AND fork = false
  - stage: publish documentation
    script: "./Scripts/travis/publish-documentation.sh"
    os: osx
    osx_image: xcode12.3
    if: branch = master AND type = push AND fork = false